#!/bin/bash

case "$1" in
  up)
    operation="up -d"
    ;;
  down)
    operation="down"
    ;;
  rm)
    ;;
  kill-all)
    docker stop $(docker ps -a -q)
    docker rm $(docker ps -a -q)
    docker rmi -f $(docker images -a -q)
    docker volume rm -f $(docker volume ls -q)
    exit 0
    ;;
  *)
    echo "Invalid operation."
    exit 1
    ;;
esac

case "$2" in
  mongo)
    service="./mongo/docker-compose.yml"
    dotenv="--env-file ./credentials/mongo.env"
    container="mongo"
    image="mongo"
    volumes="mongo_db mongo_configdb"
    networks="mongo_network"
    ;;
  mongo-express)
    service="./mongo-express/docker-compose.yml"
    dotenv="--env-file ./credentials/mongo.env --env-file ./credentials/mongo-express.env"
    container="mongo-express"
    image="mongo-express"
    ;;
  gitea)
    service="./gitea/docker-compose.yml"
    dotenv="--env-file ./credentials/gitea.env"
    container="gitea"
    image="gitea/gitea"
    volumes="gitea_config gitea_data gitea_var"
    init_mariadb=('./credentials/gitea.env' 'GITEA__database__USER' 'GITEA__database__PASSWD' 'GITEA__database__NAME')
    ;;
  passbolt)
    service="./passbolt/docker-compose.yml"
    dotenv="--env-file ./credentials/passbolt.env"
    container="passbolt"
    image="passbolt/passbolt"
    volumes="gpg_volume jwt_volume"
    init_mariadb=('./credentials/passbolt.env' 'PASSBOLT__DATASOURCES_DEFAULT_USERNAME' 'PASSBOLT__DATASOURCES_DEFAULT_PASSWORD' 'PASSBOLT__DATASOURCES_DEFAULT_DATABASE')
    ;;
  mariadb)
    service="./mariadb/docker-compose.yml"
    dotenv="--env-file ./credentials/mariadb.env --env-file ./credentials/gitea.env"
    container="mariadb"
    image="mariadb-mariadb"
    volumes="mariadb_data"
    networks="mariadb_network"
    ;;
  *)
    echo "Invalid service."
    exit 1
    ;;
esac

if [[ "$1" == "up" || "$1" == "down" ]]; then
  cmd="docker compose -f $service $dotenv $operation"
  if [[ "$1" == "up" && ! -z "$init_mariadb" ]]; then
    source ${init_mariadb[0]}
    DB_USER=${!init_mariadb[1]}
    DB_PWD=${!init_mariadb[2]}
    DB_NAME=${!init_mariadb[3]}
    cmd+="; docker exec mariadb /usr/local/bin/init_db.sh ${DB_USER} ${DB_PWD} ${DB_NAME}"
  fi
elif [[ "$1" == "rm" ]]; then
  cmd="docker stop $container"
  cmd+="; docker rm $container"
  cmd+="; docker rmi -f $image"
  if [[ ! -z "$volumes" ]]; then
    cmd+="; docker volume rm -f $volumes"
  fi
  if [[ ! -z "$networks" ]]; then
    cmd+="; docker network rm $networks"
  fi
fi

eval $cmd