services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    env_file:
      - path: ../credentials/mongo.env
      - path: ../credentials/mongo-express.env
    ports:
      - ${ME_HOST_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_WEB_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_WEB_PASSWORD}
    networks:
      - mongo_network

networks:
  mongo_network:
    external: true