services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    env_file:
      - path: ../credentials/nginx.env
    ports:
      - ${NGINX__HTTP_PORT}:80
      - ${NGINX__HTTPS_PORT}:443
    volumes:
      - nginx_data:/etc/nginx/conf.d
    networks:
      - nginx_network
  
volumes:
  nginx_data:
    name: nginx_data

networks:
  nginx_network:
    driver: bridge
    name: nginx_network
